-- STRING FUNCTIONS
SELECT LENGTH('SKYFALL');
select FIRST_NAME, LENGTH(FIRST_NAME)
FROM employee_demographics
order by 2;
SELECT UPPER('sky');
SELECT LOWER('SKY');
select FIRST_NAME, UPPER(FIRST_NAME)
FROM employee_demographics;
SELECT TRIM('           SKY           ');
SELECT RTRIM('           SKY           ');
SELECT LTRIM('           SKY           ');
SELECT FIRST_NAME, 
LEFT(FIRST_NAME,4),
RIGHT(FIRST_NAME,4),
SUBSTRING(FIRST_NAME,3, 2),
BIRTH_DATE,
SUBSTRING(BIRTH_DATE,6, 2) AS BIRTH_MONTH
FROM employee_demographics;


SELECT FIRST_NAME, REPLACE(FIRST_NAME, 'a','z')
FROM employee_demographics;

SELECT LOCATE('X','ALEXANDER');
SELECT FIRST_NAME, LOCATE('AN',FIRST_NAME)
FROM employee_demographics;

SELECT FIRST_NAME, LAST_NAME,
CONCAT(FIRST_NAME,' ',LAST_NAME) AS Full_name
FROM EMPLOYEE_DEMOGRAPHICS;

 